sudo: required
language: generic

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project monetize-304415
  - gcloud config set compute/zone europe-west1-b
  - gcloud container clusters get-credentials monetize-cluster

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker build -t rosenurkov/web-client-test -f ./web-client/Dockerfile.dev ./web-client
  - docker build -t rosenurkov/api-gateway-test -f ./api-gateway/Dockerfile.dev ./api-gateway
  - docker build -t rosenurkov/balance-service-test -f ./balance-service/Dockerfile.dev ./balance-service
  - docker build -t rosenurkov/budget-service-test -f ./budget-service/Dockerfile.dev ./budget-service
  - docker build -t rosenurkov/statistics-service-test -f ./statistics-service/Dockerfile.dev ./statistics-service

script:
  - docker run -e CI=true rosenurkov/web-client-test npm test -- --coverage
  - docker run -e CI=true rosenurkov/api-gateway-test npm test
  - docker run -e CI=true rosenurkov/balance-service-test npm test
  - docker run -e CI=true rosenurkov/budget-service-test npm test
  - docker run -e CI=true rosenurkov/statistics-service-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
