sudo: required
language: generic

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - docker build -t rosenurkov/web-client-test -f ./web-client/Dockerfile.dev ./web-client
  - docker build -t rosenurkov/api-gateway-test -f ./api-gateway/Dockerfile.dev ./api-gateway
  - docker build -t rosenurkov/balance-service-test -f ./balance-service/Dockerfile.dev ./balance-service
  - docker build -t rosenurkov/budget-service-test -f ./budget-service/Dockerfile.dev ./budget-service
  - docker build -t rosenurkov/statistics-service-test -f ./statistics-service/Dockerfile.dev ./statistics-service

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker run -e CI=true rosenurkov/web-client-test npm test -- --coverage
  - docker run -e CI=true rosenurkov/api-gateway-test npm test
  - docker run -e CI=true rosenurkov/balance-service-test npm test
  - docker run -e CI=true rosenurkov/budget-service-test npm test
  - docker run -e CI=true rosenurkov/statistics-service-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
