apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: budget-service
  template:
    metadata:
      labels:
        component: budget-service
    spec:
      containers:
        - name: budget-service
          image: rosenurkov/monetize-budget-service
          ports:
            - containerPort: 4002
          env:
            - name: TYPEORM_CONNECTION
              value: mysql
            - name: TYPEORM_HOST
              value: budget-service-database-cluster-ip-service
            - name: TYPEORM_PORT
              value: "3306"
            - name: TYPEORM_USERNAME
              value: root
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: budget-service-database-password
                  key: PASSWORD
            - name: TYPEORM_DATABASE
              value: monetize-budget
            - name: TYPEORM_ENTITIES
              value: src/entities/*.entity.ts
            - name: TYPEORM_MIGRATIONS
              value: src/config/database/migrations/*.ts
            - name: TYPEORM_MIGRATIONS_DIR
              value: src/config/database/migrations
            - name: BUDGET_SERVICE_HOST
              value: budget-service-cluster-ip-service
            - name: BUDGET_SERVICE_PORT
              value: "4002"
            - name: STATISTICS_SERVICE_HOST
              value: statistics-service-cluster-ip-service
            - name: STATISTICS_SERVICE_PORT
              value: "4003"
