apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: statistics-service
  template:
    metadata:
      labels:
        component: statistics-service
    spec:
      containers:
        - name: statistics-service
          image: rosenurkov/monetize-statistics-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4003
          env:
            - name: STATISTICS_SERVICE_HOST
              value: "0.0.0.0"
            - name: STATISTICS_SERVICE_PORT
              value: "4003"
            - name: REDIS_HOST
              value: statistics-service-database-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
