// auth
export const AUTH_REQUEST_START = "AUTH_REQUEST_START";
export const AUTH_REQUEST_FAIL = "AUTH_REQUEST_FAIL";
export const AUTH_HIDE_MESSAGE = "AUTH_HIDE_MESSAGE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// payments
export const PAYMENTS_REQUEST_START = "PAYMENTS_REQUEST_START";
export const PAYMENTS_REQUEST_FAIL = "PAYMENTS_REQUEST_FAIL";
export const PAYMENTS_HIDE_MESSAGE = "PAYMENTS_HIDE_MESSAGE";

export const FETCH_PAYMENTS_SUCCESS = "FETCH_PAYMENTS_SUCCESS";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";

// budgets
export const BUDGETS_REQUEST_START = "BUDGETS_REQUEST_START";
export const BUDGETS_REQUEST_FAIL = "BUDGETS_REQUEST_FAIL";
export const BUDGETS_HIDE_MESSAGE = "BUDGETS_HIDE_MESSAGE";

export const FETCH_BUDGETS_SUCCESS = "FETCH_BUDGETS_SUCCESS";
export const CREATE_BUDGET_SUCCESS = "CREATE_BUDGET_SUCCESS";
export const UPDATE_BUDGET_SUCCESS = "UPDATE_BUDGET_SUCCESS";
export const DELETE_BUDGET_SUCCESS = "DELETE_BUDGET_SUCCESS";
